### ISSUE TITLE
New feature requests

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#1]
When coloring the mineral nodes by the mean redox state the color key for the mean mineral redox state gets partially cut off at the bottom.  You can see all of the colors, but the numbers below the color are partially cut off:
![image](https://user-images.githubusercontent.com/44819149/51353530-e6175100-1a7e-11e9-9fe2-f3ca502a9321.png)

**Comment by sjspielman** [comment]
Note, I’m going to close this because I’ve figured out to have a fully interactive network in the application. I’ll be overhauling the code entirely over the next few days. If the issue persists after the overhaul we can reopen the issue!

**Comment by mooreek** [comment]
> Note, I’m going to close this because I’ve figured out to have a fully interactive network in the application. I’ll be overhauling the code entirely over the next few days. If the issue persists after the overhaul we can reopen the issue!

**Comment by mooreek** [comment]
Sounds great! 
I am glad I finally had some time to look at this, this is an amazing application!  Great job!

After you make these changes and we test everything to make sure it is working smoothly, and when you have time, these are some other additional requests:
-Is it possible to allow the element labels to be sized by degree?  
-Is it possible to color the network edges by mean redox state?
-Is it possible to color the mineral nodes and/or network edges by max age?
-Is it possible to include multiple elements in a network?

**Comment by sjspielman** [comment]
>-Is it possible to allow the element labels to be sized by degree?

The label size is controlled by node size, but node sizing options are forthcoming.
 
> -Is it possible to color the network edges by mean redox state?

This feature is already present in the implementation you have access to, so yes.

> -Is it possible to color the mineral nodes and/or network edges by max age?

Mineral node color by max age is also already present. Sizing edges by other features besides redox is straightforward to add and is forthcoming,

>-Is it possible to include multiple elements in a network?

Yes, but we will need an upper limit for how many "focal elements" should be included. I plan to add two more tabs to this application for different "modes" of analysis: compare networks over time (actually show four full networks in same pane), and this suggestion of exploring multiple "focal" elements. I'm thinking 5 for an upper limit.

**Comment by sjspielman** [comment]
All features in this issue thread have been implemented.
