### ISSUE TITLE
dragon crashing whenever I select "Standard deviation Pauling electronegativity" in the Analyze Network tab

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#11]
Hi,
This just started recently, but whenever I select go to the "Analyze Network" tab and select "Standard deviation electronegativity" as the response variable the site crashes and has to be reloaded.  This didn't happen before with this function until a couple days ago.  

I noticed that in the response variable list the variable is called "Standard deviation electronegativity" and the the predictor variable list the variable is called "Standard deviation Pauling electronegativity".  I don't know if the different names could be causing any issues.  The issue only happens when "Standard deviation electronegativity" is selected as a response variable, but everything appears to work fine when "Standard deviation Pauling electronegativity" is selected as a predictor variable

I started going through all the combinations of response and predictor variables, and there was one other variable combination where the site crashed as well.
Response                        Predictor
Louvain                           Louvain

Strange that this combination would cause an issue, Louvain works fine as either a response or predictor variable when it is paired with a different variable.

Thanks,
Eli

**Comment by sjspielman** [comment]
Ha, it's fine - I found this bug over the weekend and fixed it, but forgot to push to website! Give it a minute.

**Comment by sjspielman** [comment]
Note, the Louvain issue you found is more complicated, and I am aware of it but will take time.

**Comment by mooreek** [comment]
Great that you already found the standard deviation issue, I was initially very surprised at how fast the issue was closed!

**Comment by sjspielman** [comment]
Ok, more general bug fixes applied. Should be working now, once deployed in a few minutes.
