### ISSUE TITLE
dragon page is not loading

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#12]
dragon is not working this morning.  Either the web page is not loading, or when it does load and I initialize a network the network does not appear.  Do you know if there is something going on with Shiny at the moment, or some other issue?  
Best,
Eli

**Comment by mooreek** [comment]
The dragon page is loading now, but the full network is not loading for different layout algorithms other than the default FR layout.  Thanks!
Best,
Eli

**Comment by sjspielman** [comment]
Website is working fine for me, could be your internet?

As a backup plan, there is a version on CRAN now so you can  always get the package that way and use RStudio Cloud, OR use the remotes package to get the latest and greatest:

```
install.packages("remotes")
library(remotes)
install_github("spielmanlab/dragon")
library(dragon)
rundragon()
```

**Comment by sjspielman** [comment]
> The dragon page is loading now, but the full network is not loading for different layout algorithms other than the default FR layout. Thanks!
> Best,
> Eli

Again, works for me with all layouts. Sounds like your internet...

**Comment by mooreek** [comment]
The page is loading now, I was just being too impatient.  Great suggestion about running on rstudio.cloud.
Thanks,
Eli
