### ISSUE TITLE
dragon is crashing whenever I load the full mineral network

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#13]
Hello, when I load the full mineral network without making any network adjustments or changing colors etc. dragon crashes.  It is even crashing in rstudio.cloud after I load the network and attempt to move a node.  I had been able to move nodes around slowly in the past on the full mineral network, so I am not sure if there is some new issue that as come up.  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
No changes have been made to dragon for about 2 weeks, so I suspect this is due to their servers, OR you may be using an outdated version of dragon. You can always re-install the package from github; let me know if this helps.
