### ISSUE TITLE
dragon is crashing when I try to make a plot of community cluster and max age for the Arsenic network

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#16]
Hi,

I made a present day Arsenic network (regular nodes, they are not separated by redox state).  I also selected Leading Eigen as the cluster algorithm.  Then in the analysis tab I selected community clusters as the independent variable and maximum age as the dependent variable and dragon suddenly crashed.  

If I select Louvain as the clustering algorithm dragon does not crash.  If I select leading eigen as the algorithm and then separate the nodes by redox state before going to the analysis tab and creating the cluster/max age plot dragon also does not crash.  Is there some issue with leading eigen and the network with regular nodes not separated by redox state?

Thanks,
Eli

**Comment by sjspielman** [comment]
Yes, there seems to be a bug - I will look into this soon, but may not get a chance for another day or two.

**Comment by sjspielman** [comment]
Bug fixed.
