### ISSUE TITLE
Age Slider

### ISSUE THREAD

**Issue by TheGolden1** [spielmanlab/dragon#17]
I'm not sure what the age slider is doing, it seems backwards. If I slide all the way to the right to 4.5, the plot is of minerals with the age zero.  What does age for the youngest minerals mean? I was expecting to slide to 4.5 Ga to view minerals that existed at 4.5Ga, i.e. probably from meteorites.

**Comment by sjspielman** [comment]
When you slide to 4.5 Ga, you should get the smallest networks just like you anticipate, including only those minerals which are known to have existed 4.5 Ga according to the database. Your expectation is completely correct, and this is the behavior I consistently observe  - just checked for myself, and indeed the age slider behaves like we expect.  
I'm not sure what exactly you mean by "age zero" minerals, given that I only see ones with 4.5Ga dates. Can you include reproducible information about which settings you applied, where you see younger minerals, and maybe a screen shot of what you are seeing? This will help me understand what you are experiencing and we can see what exactly is going on.

**Comment by TheGolden1** [comment]
I think I got confused because, when I slid the age to 4.5, and selected the node for chrysocolla, then viewed the "selected node information" (SNI) I thought it was dynamic and would show me just the information for that time step (4.5). Since, the data in the SNI is sorted by youngest to oldest and contained all of the data fro that mineral, not just for that time step, I was confused. After realizing this, I understand.

Would the ability to display just the info for that time step in the SNI be reasonable or would it end up causing other problems?

It may also be useful to have an upper and lower end to the age slider so that one could select a time interval and display the network and the SNI for that interval...

**Comment by sjspielman** [comment]
Aha, good catch!!! This feels like a bug in the table to me - I agree it should only display minerals *at their age in a given network* and not other instances where they are younger.

Time interval is also a great idea, for upper and lower bounds. I should be able to address both these issues - bug and new feature - by Thursday.

**Comment by TheGolden1** [comment]
As a side note, I have updated the MED and there are new cache files in the exporting directory.

**Comment by sjspielman** [comment]
Table bug has been fixed, and age range slider has been implemented.

Thanks for update on new MED data!! Currently the way data is read in to dragon requires the data to be part of the official release on CRAN, so the updated data is not (yet) in there, but is coming soon.

**Comment by sjspielman** [comment]
@TheGolden1 and @mooreek - I'm reopening this issue because I'm now unsure whether I implemented the age slider incorrectly given what it *should* do and/or whether the age slider makes sense. For example, consider an age range of 1-1.2 Ga. The age slider will show all minerals that have at least one sample whose maximum age is between 1-1.2. This is how the implementation works now. *However*, this may be misleading because it almost certainly will NOT indicate all the minerals which existed on Earth 1-1.2 Ga - only those identified to be in that age range.

Do either of you have more thoughts, or am I overthinking this? The main question is - what should the age slider display?

-Stephanie

**Comment by mooreek** [comment]
@sjspielman and @TheGolden1 - The way you have the age slider working is exactly how I envisioned it as well.  If a user chooses the age range of 1-1.2 Ga I hoped it would only include minerals with a maximum age between 1-1.2 Ga.  If the user wants to look at all the minerals on Earth during that time period they can choose the time period of 1-4.5 Ga (this will show all minerals present with maximum ages over 1 Ga).  Do you agree with this @TheGolden1?
Thanks,
Eli

**Comment by TheGolden1** [comment]
I agree, looks good!
