### ISSUE TITLE
Were element nodes removed from clustering?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#18]
The element nodes are colored according to element cluster, but when I look at the node clustering and centrality table elements are not included in the table.  I'm guessing this does not affect the linear analyses?

**Comment by sjspielman** [comment]
That elements weren't appearing in the table was a bug; fixed now. That said, this is not relevant to linear models. By definition, elements are not part of *any* linear models - the purpose of models is to study the minerals only. Elements cannot be included for pretty straightforward reasons - they possess entirely different attributes from minerals, i.e. there is not a maximum age, a distribution of of electronegativities, number of localities, etc.  In addition, generally each type of node is analyzed separately in bipartite networks, often for reasons like this.

**Comment by mooreek** [comment]
Great, thanks for the clarification.  I was worried that if the elements were left out the clusters would change somehow, but that is clearly not an issue.
