### ISSUE TITLE
New age slider leaving out minerals >4.5 Ga?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#19]
@sjspielman and @TheGolden1 - Thank you for bringing up the other issue about the age slider, it helped me realize another age slider issue.  

It appears that the new age slider is leaving out minerals with ages greater than 4.5 Ga.  For example, when I made a Sulfur network with the age range 4-4.5 Ga the oldest minerals in the mineral table are 4.46 Ga.  However, there are Sulfur minerals with maximum ages >4.5 Ga that are not in the network.  For example, Baryte has a max age of 4.88 Ga (as given from http://rruff.info/ima/), but Baryte is not listed in the node table below the network.  Perhaps the age slider should be extended back to 4.9 Ga to ensure that all the minerals are included.  As far as I know, the oldest minerals from http://rruff.info/ima/ have a max age of 4.88 Ga.  
Thanks,
Eli

**Comment by sjspielman** [comment]
Yes, bug. Fixed!

**Comment by mooreek** [comment]
Great, the new age slider is now up and running.  In the case of Sulfur, the two minerals with the age 4.88 Ga are still not in the node table below (Baryte and Marcasite).  Could they be getting left out somehow?  I noticed some Fe minerals with max ages of 4.88 Ga are left out of the Fe network as well.  

Thanks for working on this so quickly.
Best,
Eli

**Comment by sjspielman** [comment]
Argh, my bad. Fixed now!

**Comment by mooreek** [comment]
Great, thanks for fixing that!  Everything appears to be working well now.
