### ISSUE TITLE
Mineral node labels are all the same

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#2]
I wanted to make a vanadium network with the mineral labels included.  When I increased the size of the mineral label font all of the minerals had the same name (Beckettite).  If you click on different mineral nodes you get the correct mineral name listed below, but for some reason all of the mineral labels are Beckettite in the network.  This is probably some minor bug that will be quick to fix.

**Comment by sjspielman** [comment]
Bug has been fixed on github version (for running locally), but not yet deployed to website. I will close the issue once it has been officially deployed.

**Comment by sjspielman** [comment]
Deployed!
