### ISSUE TITLE
Color Keys of Network Clusters and Analysis Tukey Plot Clusters are sometimes Different

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#20]
Hi,

It appears that the color of the network clusters are different on the network figure vs. the analysis plot when network clusters are chosen as the predictor variable.  For example, when I make an Arsenic (As) network - cluster 1 is red for the network and plot (same), but cluster 7 appears to be teal in the network and purple in the plot (different).  Do you know why this could be happening, or am I just reading the keys wrong?  I am using Leading Eigen as the clustering method in this case.  When I use Louvain clustering the colors are the same for the network and the plot.

When I use Leading Eigen for the As network there are 14 network clusters produced, could this be complicating the color key for the plot?

Thanks,
Eli

**Comment by sjspielman** [comment]
Currently there is no link between colors in the network and in the plot. I should be able to link them up, though. I'll add this to my to-do new features list.

**Comment by sjspielman** [comment]
Colors should now be consistent.

**Comment by mooreek** [comment]
Yes, the colors look consistent now.  Thanks!
