### ISSUE TITLE
Hold network node positions when changing network cluster method

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#21]
Hi,

Currently when I change network clustering method all of the nodes move back to the default location.  Is it possible for the network nodes to all stay in the same positions that I have moved them to after changing network cluster methods and when coloring nodes by network cluster?

Thanks,
Eli

**Comment by sjspielman** [comment]
Hi Eli, 

Re-clustering the data will always have to rebuild the network. Initial positions can be preserved by using the same random seed, but if you are dragging nodes around there is currently no way to preserve the positions.

I have a sense of how to add the feature in you're looking for, but may take a little bit of time to code this one up. I'll start trying some things out.

-Stephanie

**Comment by sjspielman** [comment]
I'm pretty sure this has been fixed. Let me know if you encounter niche conditions where it doesn't work.

**Comment by mooreek** [comment]
Yes, the node positions are staying consistent after being moved around.  Thanks!
