### ISSUE TITLE
Small request, possible to show the number of mineral nodes and element nodes next to the network modularity score?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#22]
Hi,

At the bottom of the interactive network window, is it possible to show how many mineral nodes and element nodes there are next to the network modularity score?

Thanks,
Eli

**Comment by sjspielman** [comment]
Sure, I'll get this done in the next couple days!

**Comment by sjspielman** [comment]
Text added, note some minor app redesign as well. The tables below the network were repetitive, so I placed all information into an entirely new tab and retained only the selected node table for the main page. I think this streamlines the behavior a lot more.

**Comment by mooreek** [comment]
Great, thanks for adding the number of nodes.  The redesign looks great as well.
