### ISSUE TITLE
In the network information tab COV mineral electronegativity shows the same values as standard deviation mineral electronegativity

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#23]
Hi,
When using the network information tab, the values in the COV mineral electronegativity column are the same as the Std Dev mineral electronegativity column.  Should be a quick easy fix.

Also, when using dragon through rstudio.cloud the Std Dev mineral electronegativity column and the COV mineral electronegativity column get cut off from view and are not able to be used.  These columns show up fine when using the online dragon version, so I am not sure why it gets cut of using rstudio.cloud.

Thanks,
Eli

**Comment by mooreek** [comment]
I should add that when I copy the network information from rstudio.cloud the Std Dev mineral electronegativity column and the COV mineral electronegativity column do get successfully copied and exported, so it is just a matter of not being able to see them before copying or exporting on rstudio.cloud.
-Eli

**Comment by sjspielman** [comment]
Hi Eli, 

Fixing the sd vs. cov bug now. With regards to seeing all columns, this has to do with the size of your window/screen. You should see a little green plus sign along each row for smaller windows, click it and all column values are revealed.

-Stephanie

**Comment by mooreek** [comment]
Thanks, everything looks great!
Best,
Eli
