### ISSUE TITLE
Is it possible to add a "copy" button for the Tukey Test Tables?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#24]
Hi Stephanie,

Is it possible to add a "copy" button for the Tukey test tables like the copy button that is present for the Network Information table?  This would be very helpful for making supplementary tables for future publications.  Currently, if there are a lot of network clusters for the Tukey analysis it is not possible to see all the data in the second Tukey table.  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Feature added

**Comment by mooreek** [comment]
Awesome, thanks!
-Eli
