### ISSUE TITLE
Is it possible to add all mineral locality ID #s to the selected node information table

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#26]
Hi Stephanie,

When I click on an individual mineral node the mindat locality ID is given and if the mineral is present at that locality.  Can this information be added to the selected node information table when I select an element as well, such that if I click on an element then multiple rows are given for each mineral locality?  I think that information was given before, but maybe it has been changed?  This would make it faster to get all mineral localities for a given element instead of clicking on each individual mineral.  Thanks for your help!

Best,
Eli

**Comment by sjspielman** [comment]
Hi Eli, 

I indeed had removed this information to reduce clutter in the table below the network as it was getting a bit out of hand and redundant with the full table containing all network information.
Let's chat about this in person to determine where the best place is to show which variables!

-Stephanie
