### ISSUE TITLE
Data Plots in Analysis Tab

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#27]
Hi,

When plotting all types of dependent variables by community cluster (independent variable) the data points on the plot are all plotted on one vertical line
![image](https://user-images.githubusercontent.com/44819149/63881607-3738dd00-c99e-11e9-87fa-07453309206c.png)

Before the data points were spread out very nicely among the community clusters so you could see all the data points, so I imagine there is some bug that has changed the plot format.  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Fixed
