### ISSUE TITLE
Can you add copy buttons for the tukey test tables on the analysis tab?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#28]
Hi, 

Recently you added "copy" button for the Tukey results tables, which was very helpful for exporting the data.  The copy button has gone away with the new updates to dragon, so if you could add it again that would be great.  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Woops, I'll get that back in shortly.

**Comment by sjspielman** [comment]
Looking into now and the button was never removed. Can you confirm you experience this problem with a screenshot? Please give me all settings you've used so I can try and reproduce.

**Comment by mooreek** [comment]
Huh, the copy buttons are there now.  I am not sure what I did, but I could have swore that the buttons were not available for me for a period of time.  Sorry for the false alarm!
-Eli
