### ISSUE TITLE
Can you add "Minumum Max Age (Ga)" as an option to the network information table?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#29]
Hi Stephanie,

Is it possible to add "Minimum Max Age (Ga)" as an option to be added to the network information table?  This would be helpful for comparing trends through time at both ends of the age spectrum.

Best,
Eli

**Comment by sjspielman** [comment]
Hi Eli, 

This is a bit tricky given how variables are treated throughout dragon so I will have to give it some thought, but should be possible.

-Stephanie
