### ISSUE TITLE
Error Message when running dragon: there is no package called 'shinyBS'

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#30]
Hi Stephanie,

I downloaded the latest version of dragon using the following command:
install_github("spielmanlab/dragon", force=T)

Then ran this command, which gave no error messages: 
library(dragon)

Then when I did 'rundragon()' I got the following error message:

'Listening on http://127.0.0.1:3405
Warning: Error in library: there is no package called ‘shinyBS’
  49: stop
  48: library'

Any thoughts on what could be the issue?  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
A package is missing from your system to run dragon, which should have been specified in dragon's settings. I'll fix this now, re-run the command in a few min.

**Comment by mooreek** [comment]
I downloaded dragon again and when I did rundragon() I now have the following error message:
there is no package called ‘plotly’

Thanks,
Eli
