### ISSUE TITLE
New Error Message: there is no package called 'plotly'

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#31]
I downloaded dragon again and when I did rundragon() I now have the following error message:
 there is no package called ‘plotly’

Could this be a similar issue to the previous shinyBS message?

Thanks,
 Eli

**Comment by sjspielman** [comment]
Argh...yes.... this is why i need to write the tests....

**Comment by mooreek** [comment]
Thanks for looking into this!
