### ISSUE TITLE
Unable to install dragon on PC

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#32]
Hi Stephanie,

I was able to install dragon using R or rstudio on my computer.  Using rstudio "remotes" was installed without any issues.  When I try to install dragon I get the following error messages:

Error: Failed to install 'dragon' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘curl’
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Do you think this can be addressed or is it the same issues with the university network?

Thanks!
Eli

**Comment by sjspielman** [comment]
Not a general software problem but a personal computer setup problem - closing this public issue.
