### ISSUE TITLE
I am not able to export an HTML Network using dragon locally on my computer

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#33]
Hello,

When I click on export HTML network the save window comes up, but when I click on save the file does not get saved to the selected folder.  Could this be another university network issue or a bug?

Best,
Eli

**Comment by sjspielman** [comment]
Hmm, not sure about this - it works fine on my computer, so could go either way.
Let's look at it together in person next week.

**Comment by sjspielman** [comment]
Hi Eli, 
Indeed I found a bug here - looking into download problems now and might be solved by 11 am!
-Stephanie

**Comment by sjspielman** [comment]
Should be fixed!! Sending patch to CRAN now as well.
