### ISSUE TITLE
The copy button for network information is gone

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#34]
Hi Stephanie,

I do not see the copy button for the network information table.  The copy button is present for the selected node information table below, but not for the network information table above.  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Hi Eli, 

Found it. Seems the functionality I added to round the table columns is not compatible :( 

-Stephanie

**Comment by mooreek** [comment]
Hi again,

Now when I copy the data or export it from the table it only gives me 10 rows of data.  It copies or exports the 10 rows that are being shown on the screen.  Any thoughts on what could be causing this?  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Yes I think I know what is causing it; to accommodate more information in the tables I had to change how they are handled but this apparently ruins the copy buttons.
I will probably need to implement a new way of getting buttons.. stay tuned.

—
Stephanie J. Spielman, PhD
Assistant Professor
Department of Biological Sciences
Rowan University

Science Hall 201D
856-256-5400 Ext. 53578
http://spielmanlab.io



On Wed, Sep 25, 2019 at 5:04 PM -0400, "mooreek" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi again,

Now when I copy the data or export it from the table it only gives me 10 rows of data. It copies or exports the 10 rows that are being shown on the screen. Any thoughts on what could be causing this? Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Has to do with how data is being handled - previously, data was being handled on the client side which allows for all rows to be downloaded. But, the data got too big and had to be handled server side instead which only downloads the visible rows. This fix for this is a separate download button that will give you a CSV of the data, which can be directly imported to Excel.
