### ISSUE TITLE
Unable to download network HTML file

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#35]
Hi Stephanie,

When I try to download an HTML file of a network the spot at the bottom left of the screen that shows download progress says "downloadNetwork_....txt  Failed - Server problem".  Do you think this is a dragon problem, a Rowan network problem, or a Google Chrome problem?  Thanks for your help!

Best,
Eli

**Comment by sjspielman** [comment]
How are you using dragon? I just went to the shinyapps URL and tried to download a network and it worked fine. 
You may need to force an update to the most recent version if using locally?

**Comment by mooreek** [comment]
I was using dragon on the shinyapps URL as well.  I guess there must be some other issue with my computer or browser causing the problem?
