### ISSUE TITLE
Unable to download Tukey Test results

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#36]
Hi Stephanie,

On the Analyze tab I am unable to download the Tukey Test results presesnted in the tables next to the plot.  It looks like the download buttons were lost with the recent version.  The download plot option is still there, and the download selected node information is still there, but the download option for the Tukey Test is not there (at least I cannot find it).  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Fixed!
