### ISSUE TITLE
Figure Export Issue

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#37]
Hi Stephanie,

Unfortunately, the new figure export function is still making all the nodes different sizes, when I wanted the nodes to be different sizes based on number of mineral localities and element node degree.  I have only used the public shiney dragon version, I will try the local version tomorrow.

Thanks,
Eli

**Comment by sjspielman** [comment]
I did not get a chance to update the shinyapps version, so this is not unexpected - the version on our servers should work fine. 
Let me know when you get a chance today, and I will also update the shinyapps version when I get in to the office.

**Comment by mooreek** [comment]
Great, I am using the local dragon server and it is working.  However, the size changes are much smaller in the output figure than what I input on dragon.  Not sure why that is the case.  Thanks!
-Eli

**Comment by sjspielman** [comment]
Correct - this is unavoidable. Increase the scale of point size OR change the dimensions of the output figure. That’s how you can fiddle with point size. If it doesn’t work send me a specific example.

—
Stephanie J. Spielman, PhD
Assistant Professor
Department of Biological Sciences
Rowan University

Science Hall 201D
856-256-5400 Ext. 53578
http://spielmanlab.io

________________________________

**Comment by mooreek** [comment]
Great, I will try the different sizes and output dimensions.
Best,
Eli

**Comment by sjspielman** [comment]
This has been implemented.
