### ISSUE TITLE
Export of tables only exporting 10 rows of data, rest of data is not being exported

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#40]
Hi Stephanie,

When I try to export data from the tables on any of the tabs only the 10 rows that are being shown on the screen are exported.  Can you change the export so that all rows from the table are exported at once?  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Looking into this, the issue may not be able to resolved with the current buttons - the data has grown too large for these buttons to be used to export all rows for some of the tables. Instead, I can add a button to download the tables as CSV or Excel for those tables which are too large, specifically the node attribute tables (linear models should be fine to keep the buttons). Sound ok?

**Comment by mooreek** [comment]
Yes, sounds good.  I tried exporting a CSV file as well and it only exported the 10 rows that were visible on the screen, so it looks like the CSV export has the same issue.  Thanks!

**Comment by sjspielman** [comment]
Issue solved.

**Comment by mooreek** [comment]
Awesome, thanks!
