### ISSUE TITLE
Sulfur, Chlorine, and Nitrogen should be intermediate bases

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#41]
Hi Stephanie,

Previously we had S, Cl, and N categorized as intermediate bases on dragon, but they are currently categorized as "N/A".  Is it possible to change them back to intermediate bases?  Thanks!

Best,
Eli

**Comment by sjspielman** [comment]
Yes, fixing now!! Was a bug for all intermediate bases. Stay tuned.

**Comment by sjspielman** [comment]
Fixed; deploying to dragon-dev now.
