### ISSUE TITLE
Problem with the development version of magrittr

### ISSUE THREAD

**Issue by lionel-** [spielmanlab/dragon#42]
I see a problem with dev magrittr. I have traced it to these lines:

```r
## Explicit pipe and operator definitions ---------------------------------------------------------
`%>%`    <- magrittr::`%>%`
`%<>%`   <- magrittr::`%>%`
`%...>%` <- promises::`%...>%`
`:=`     <- rlang::`:=`
`!!`     <- rlang::`!!`
```

The `%<>%` operator is imported as `%>%`, which used to work because of internal implementation details. This no longer works.

Note that you're not supposed to assign foreign functions in your namespace. You should import them instead. Otherwise, their definition is set in stone when your package is built. The definitions copied inside your package will never be updated until your package is reinstalled which might cause all sorts of problems (they might refer to functions or variables that no longer exist etc).

We're planning to release the next version of magrittr in one month, it'd be great if you could fix this on CRAN before then :)

By the way, there is no need for importing `:=` and `!!`.

**Comment by sjspielman** [comment]
Hi @lionel- , Thanks very much for bringing all of this to my attention!!! I will address it promptly and it should be on its way to CRAN in the next 1-3 weeks with a couple other patch updates.

EDIT: Congratulations on being issue #42! An honor! :)

**Comment by lionel-** [comment]
Thanks!
