### ISSUE TITLE
Unable to get network closeness centrality values

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#45]
Hi Stephanie,
I am trying to download the network closeness centrality values for the Fe network.  When I use either the mineral attributes table or the explore individual nodes custom table, all of the network closeness values are 0 for either the regular network or the network with separate element nodes for each redox state.  The network closeness values are generally very small (ex: 0.0004), and it appears that maybe they are all being rounded off to zero?  Is there a way to download these values with an appropriate number of significant figures?  Thanks for your help!
Best,
Eli

**Comment by sjspielman** [comment]
Will look into it in the next few days. The goal should be for the display table to round, but NOT the downloaded table...
—
Stephanie J. Spielman, PhD
Assistant Professor
Department of Biological Sciences
Rowan University
https://spielmanlab.github.io


On Feb 24, 2021, at 12:19 AM, mooreek <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Stephanie,
I am trying to download the network closeness centrality values for the Fe network. When I use either the mineral attributes table or the explore individual nodes custom table, all of the network closeness values are 0. These values are generally very small (ex: 0.0004), and it appears that they are all being rounded off to zero. Is there a way to download these values with 3 significant figures? Thanks for your help!
Best,
Eli

**Comment by sjspielman** [comment]
This is now fixed on the [dragon-dev](http://sjspielman.shinyapps.io/dragon-dev) shinyapps, and will be included with next `dragon` release. There are now sliders to choose the numbers of digits, and I've confirmed it works both in displayed and exported tables. Let me know if you find any weird edge case!

**Comment by mooreek** [comment]
Great thanks, I will try it out!
