### ISSUE TITLE
Test suite broke when using igraph 1.2.11

### ISSUE THREAD

**Issue by vtraag** [spielmanlab/dragon#46]
In the latest release of `igraph`, version 1.2.11, the test suite broke due to a change in the `cluster_louvain` function which now has a stochastic implementation (details in PR https://github.com/igraph/igraph/pull/1696). Hence, the modularity is no longer necessarily exactly `0.4432351`, but some value that depends on the random number generator. In order to get reproducible results, so that the test suite doesn't fail, you should seed the RNG prior to running `cluster_louvain` using `set.seed`.

**Comment by szhorvat** [comment]
This should refer only to version 1.3.0, no? I believe 1.2.11 still uses the deterministic implementation.

**Comment by sjspielman** [comment]
Thanks for catching this! On the way to a fix.

**Comment by sjspielman** [comment]
Fixed.
