### ISSUE TITLE
Is it possible to make the element node labels overlay on top of the mineral nodes?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#5]
When the element node shapes are removed and only the element node labels remain the mineral nodes lay on top of the element labels, which makes them harder to see/read.  Is it possible to make the element node labels lay on top of the mineral nodes when the element node shapes are removed? Thanks!

**Comment by sjspielman** [comment]
In my view this is already the behavior. Send me the specific settings you have turned on and maybe a screenshot so I can reproduce what you are seeing and look into it? You should able to attach here.

**Comment by mooreek** [comment]
Yes, thank you for pointing that out.  I went through all the normal settings that I use and the element labels stayed in front of the mineral nodes until I applied "Use separate nodes for each element redox".  Hopefully you can see the change below in the screenshots before and after separate redox nodes are activated.  Thanks!

![image](https://user-images.githubusercontent.com/44819149/54635038-b8885d00-4a59-11e9-8891-f2a0eecbbf30.png)

![image](https://user-images.githubusercontent.com/44819149/54635132-eb325580-4a59-11e9-9cac-71c8fb492ace.png)

**Comment by sjspielman** [comment]
Definitely see the difference. On it! Stay tuned.

**Comment by sjspielman** [comment]
Bug fixed and app re-deployed.
