### ISSUE TITLE
“Copy”, “CSV”, and “Print” buttons are not present on "Node Clustering and Degree" tab

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#6]
Hi again,
I just noticed a bug on dragon.  I am going through and exporting all of the cluster analysis information for the full mineral network, but when I click on the “Node Clustering and Degree” tab the “Copy”, “CSV”, and “Print” buttons are not present.  Fortunately, the “Copy”, “CSV”, and “Print” buttons are present for the “Selected Node Information” tab and “Associated Mineral Localities” tab.
Thanks!
Best,
Eli

**Comment by sjspielman** [comment]
Bug fixed, and application re-deployed to shinyapps.io website.
