### ISSUE TITLE
Possible to add locality age in "Associated Mineral Localities" tab?

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#7]
Hi,
Is it possible to add the age for each locality in the "Associated Mineral Localities" tab?  No big rush if this is a lengthy process if the data is even available.  Thanks!
Best,
Eli

**Comment by sjspielman** [comment]
Added - should be online within a few minutes.

**Comment by mooreek** [comment]
It looks great, thanks for adding this age data!
