### ISSUE TITLE
Multiple stdev electronegativity values for certain minerals

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#9]
Hi,
I clicked on some minerals in the full network to look at their stdev electronegativity and they have different stdev electronegativity values at different localities.  For example, I clicked on Agmantinite and for some localities the stdev electronegativity is 0.42634 (this is the correct value), and for other localities it is 0.30144, 0.31447, or 0.43274.  The mean electronegativity also changes between localities for Agmantinite.  The formula for Agmantinite is pretty complex (Ag^1+^_2_Mn^2+^Sn^4+^S^2-^_4_), perhaps this could be causing issues?

I clicked on some other examples like Aurostibite (AuSb2, stdev = 0.34648) and the stdev was correct and consistent at every localite, so it is not a problem with every mineral.  

The mineral Afghanite has a pretty complex formula (Na_22_Ca_10_(Si_24_Al_24_)O_96_(S^6+^O_4_)_6_Cl_6_), but the calculated stdev was consistent and correct (1.00064), so I am not sure what the issue is with Agmantinite.  

Chambersite (Mn^2+^_3_B_7_O_13_Cl) is another example with inconsistent stdev at different localities (correct stdev 0.89894 is present for certain localities).  Perhaps Mn^2+^ (or other element redox states) could be causing some problem?  (Mn^2+^ is in both Agmantinite and Chambersite, just a thought).  

Thanks!
Best,
Eli

**Comment by sjspielman** [comment]
Is this in the Sulfur network?

**Comment by mooreek** [comment]
I noticed Agmantanite in the full mineral network, but it does contain sulfur.  Chambersite does not contain sulfur, but had a similar inconsistent electronegativity standard deviation issue.  I also noticed Chambersite in the full mineral network.

**Comment by sjspielman** [comment]
Bug fixed.. let me know if it's actually not!!
